//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibrarySystem.DatabaseEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int ISBN { get; set; }
        public Nullable<int> countPages { get; set; }
        public Nullable<System.DateTime> datePublished { get; set; }
        public int AuthorId { get; set; }
        public int OwnerId { get; set; }
        public Nullable<bool> isDeleted { get; set; }
    
        public virtual Author Author { get; set; }
        public virtual Owner Owner { get; set; }
    }
}
